# Generated by Django 3.1.3 on 2021-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
                ('product_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
